### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'use_as_tagger'

### ISSUE THREAD

**Issue by mglowacki100** [yala/text_nn#4]
Running from command line:
`CUDA_VISIBLE_DEVICES=2 python -u scripts/main.py  --batch_size 64 --cuda --dataset full_beer --embedding 
glove --dropout 0.05 --weight_decay 5e-06 --num_layers 1 --model_form cnn --hidden_dim 100 --epochs 50 --init_lr 0.0001 --num_workers
 0 --objective cross_entropy --patience 5 --save_dir snapshot --train --test --results_path logs/adhoc_0.results  --gumbel_decay 1e-5 --get_rationales
 --aspect aroma --selection_lambda .005 --continuity_lambda .01`

Gives an error:

`
Traceback (most recent call last):
  File "scripts/main.py", line 30, in <module>
    gen, model = model_utils.get_model(args, embeddings, train_data)
  File "/home/mglowacki/Desktop/RNN_yala_pytorch_2/rationale_net/utils/model.py", line 12, in get_model
    if args.use_as_tagger == True:
AttributeError: 'Namespace' object has no attribute 'use_as_tagger'
`
I've checked sourcecode but there is no --use_as_tagger parameter in args.
Btw. in the same file `model.py` there is an additional problem because `nn` is not imported.

**Comment by hwjiang1510** [comment]
hi, have you resolved it？

**Comment by hwjiang1510** [comment]
in generic.py you should add a line
"parser.add_argument('--use_as_tagger', type=int, default=0 , help='whether use it as tagger') "

**Comment by yala** [comment]
I've refactored the repo a bit, so it should work now out of the box given the new command in the readme

**Comment by mglowacki100** [comment]
It works now also with full_beer dataset. Thanks a lot!
