### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'pickle_files/embeddings.p'

### ISSUE THREAD

**Issue by hwjiang1510** [yala/text_nn#5]
In dataset.py we read
    embedding_path = 'pickle_files/embeddings.p'
    word_to_indx_path = 'pickle_files/vocabIndxDict.p'
    embedding_tensor = pickle.load(open(embedding_path,'rb'))
    word_to_indx = pickle.load(open(word_to_indx_path,'rb'))
However, the two files are not in the zip-code?

**Comment by yala** [comment]
Download Glove Embeddings from the stanford website and place it in 

`data/embeddings/glove.6B/glove.6B.300d.txt`
